version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3010:7878"
    environment:
      - OLLAMA_HOST=http://192.168.0.8:11434
      # Just remove `=xxx` to have the env variable passed forward
volumes:
  ollama:
